### ISSUE TITLE
Detail view

### ISSUE THREAD

**Issue by Andrew-Musselman** [Andrew-Musselman/rancid-tomatillos#2]
- [ ] A user should be able to click on a movie card to get more details
   - [ ] When a movie’s details are displayed, none of the other movies will be visible; it should just be that movie’s details (header/footer/etc can still be visible, of course!)
       - [ ] Modal
   - [ ] When a movie’s details are displayed, the user should have a way to return to the main view of all movies

**Comment by JessFatta** [comment]
Awesome! Let's do some more styling after we get through iteration 3 and implement API
